name: docker workflow

on:
    workflow_dispatch:
    push:
        branches: 
            - feature-branchA
            - main


env:
    MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    docker:
        name: containerization
        permissions:
            packages: write
        runs-on: ubuntu-latest
        steps: 
            - name: checkout Repo
              uses: actions/checkout@v5

            - name: docker login
              uses: docker/login-action@v3.5.0
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: GHCR login
              uses: docker/login-action@v3.5.0
              with:
                registry: ghcr.io
                username: ${{github.repository_owner}}
                password: ${{github.token}}