name: solar system workflow

on:
    workflow_dispatch:
    push:
        branches: 
            - feature-branchA
            - main


env:
    MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: unit_testing
        strategy:
            matrix:
                nodejs_version: [18, 19, 20]
                os: [ubuntu-latest, macos-latest, windows-latest]

                exclude:
                    - nodejs_version: 18
                      os: macos-latest

        runs-on: ${{ matrix.os }}

        steps:
            - name: checkout Repo
              uses: actions/checkout@v5

            - name: Setup NodeJs version - ${{ matrix.nodejs_version }}
              uses: actions/setup-node@v4.4.0
              with:
                node-version: ${{ matrix.nodejs_version }} 

            - name: install dep
              run: npm install


            - name: unit testing
              id: NodeJs-unit-testing-steps
              run: npm test


            - name: Archive test result
              if: ${{ steps.NodeJs-unit-testing-steps.outcome == 'failure' || steps.NodeJs-unit-testing-steps.outcome == 'success' }}
              uses: actions/upload-artifact@v4.6.2
              with:
                name: SP-Test-Result-${{ github.sha }}-${{ matrix.os }}-node${{ matrix.nodejs_version }}
                path: test-results.xml


    code-coverage:
        name: code coverage
        needs: unit-testing
        runs-on: ubuntu-latest
        steps:
            - name: checkout Repo
              uses: actions/checkout@v5

            - name: Setup NodeJs version - 18
              uses: actions/setup-node@v4.4.0
              with:
                node-version: 18

            - name: install dep
              run: npm install

            - name: check code coverage
              continue-on-error: true
              run: npm run coverage

            - name: archive coverage results
              uses: actions/upload-artifact@v4.6.2
              with:
                name: code-coverage-Result
                path: coverage
                retention-days: 5