name: solar system workflow

on:
    workflow_dispatch:
    push:
        branches: 
            - feature-branchA
            - main


env:
    MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: unit_testing
        strategy:
            matrix:
                nodejs_version: [18, 19, 20]
                os: [ubuntu-latest, macos-latest, windows-latest]

                exclude:
                    - nodejs_version: 18
                      os: macos-latest

        runs-on: ${{ matrix.os }}

        steps:
            - name: checkout Repo
              uses: actions/checkout@v5

            - name: Setup NodeJs version - ${{ matrix.nodejs_version }}
              uses: actions/setup-node@v4.4.0
              with:
                node-version: ${{ matrix.nodejs_version }} 

            - name: install dep
              run: npm install


            - name: unit testing
              id: NodeJs-unit-testing-steps
              run: npm test


            - name: Archive test result
              if: ${{ steps.NodeJs-unit-testing-steps.outcome == 'failure' || steps.NodeJs-unit-testing-steps.outcome == 'success' }}
              uses: actions/upload-artifact@v4.6.2
              with:
                name: SP-Test-Result-${{ github.sha }}-${{ matrix.os }}-node${{ matrix.nodejs_version }}
                path: test-results.xml


    code-coverage:
        name: code coverage
        needs: unit-testing
        runs-on: ubuntu-latest
        steps:
            - name: checkout Repo
              uses: actions/checkout@v5

            - name: Setup NodeJs version - 18
              uses: actions/setup-node@v4.4.0
              with:
                node-version: 18

            - name: install dep
              run: npm install

            - name: check code coverage
              continue-on-error: true
              run: npm run coverage

            - name: archive coverage results
              uses: actions/upload-artifact@v4.6.2
              with:
                name: code-coverage-Result
                path: coverage
                retention-days: 5

    docker:
        name: containerization
        needs: [code-coverage, unit-testing]
        permissions:
            packages: write
        runs-on: ubuntu-latest
        steps: 
            - name: checkout Repo
              uses: actions/checkout@v5

            - name: docker login
              uses: docker/login-action@v3.5.0
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}


            - name: GHCR login
              uses: docker/login-action@v3.5.0
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ github.token }}

            - name: Build Docker file
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: |
                    ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
                    ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}

            - name: test docker image
              run: |
                docker images 
                docker run --name solar-system-app -d \
                -p 3000:3000 \
                -e MONGO_URI=$MONGO_URI \
                -e MONGO_USERNAME=$MONGO_USERNAME \
                -e MONGO_PASSWORD=$MONGO_PASSWORD
                ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
                export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
                echo $IP
                echo Testing Image URL using wget
                wget -q -O - 127.0.0.1:3000/live | grep  live
